version: 5.2.1

image: Visual Studio 2019

configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore src\
build:
  verbosity: minimal
test_script:
- ps: dotnet test src\tests\tests.csproj
artifacts:
- path: '**\*.nupkg'
before_deploy:
- ps: ''
deploy:
- provider: NuGet
  api_key:
   secure: 6W7USG8YoCPjDSV9agsMdy9P1nTzDmhv9gWoHvqtECiKNSHNYVWwf69m88S84eKv
