version: 4.13.0

skip_commits:
  files:
    - appveyor.yml
    - *gitignore
    - '**/*.md'
    - '**/*.markdown

image: Visual Studio 2017

configuration: Release

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

dotnet_csproj:

  patch: true

  file: '**\*.csproj'

  version: '{version}'

  package_version: '{version}'

before_build:

- ps: dotnet restore src\

build:

  verbosity: minimal

test_script:

- ps: dotnet test src\tests\tests.csproj

artifacts:

- path: '**\*.nupkg'

  name: nuget

before_deploy:

- ps: 

deploy:

- provider: NuGet

  api_key:

    secure: zSSdZy/TonHwA3Ltpb2LbBy5zD8+YfYFBayFHPSlkUwR2bj5L9/1MSpMVCqPCCwj