version: 5.2.0

image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- ps: dotnet restore src\

skip_commits:
  files:
    - appveyor.yml
    - '*gitignore'
    - '**/*.md'
    - '**/*.markdown'
build:
  verbosity: minimal

test_script:
- ps: dotnet test src\tests\tests.csproj

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 6zFHDLM+fORKb3+N6sf/BxFt+0oNw1s0DZ0ozf1p0+nrvU16MGYf9GnklsUXWQaf
