name: "build and deploy to nuget"

on: 
  push:
    tags:
    - 'v*'

jobs:
 build_pack:  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3.0.0
  - name: Get tag
    id: latest-tag
    uses: actions-ecosystem/action-get-latest-tag@v1.6.0
    with:
      semver_only: true
  - name: Extract version
    id: extract-ver
    uses: frabert/replace-string-action@v2.0
    with:
      string: ${{ steps.latest-tag.outputs.tag }}
      pattern: v
      replace-with: ''
      
  - name: Show version    
    run: |
      echo ${{ steps.extract-ver.outputs.replaced }}
      
  - name: Patch version
    id: patch
    uses: AlexRogalskiy/github-action-tag-replacer@v2.0.1
    with:
      placeholder: '<Version1><\/Version1>'
      replacement: '<Version>${{ steps.extract-ver.outputs.replaced }}</Version>'
      sourceFile: src/CavemanTools/CavemanTools.csproj
  - name: Proj file
    run: |
      cat src/CavemanTools/CavemanTools.csproj
      exit 1
  - if: ${{ steps.patch.output.false }}
    run: |
      echo "Patching version failed"
      exit 1
  
  - name: Get .Net
    uses: actions/setup-dotnet@v2.0.0
    with: 
     dotnet-version: 6.x.x
  - name: restore packs
    run: dotnet restore src
  - name: Build
    run: dotnet build src/CavemanTools.sln --no-restore -c Release -v minimal
  - name: Test
    run: dotnet test src/Tests/Tests.csproj --no-build -c Release -v minimal
  - uses: NuGet/setup-nuget@v1.0.6
    with:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
#  - name: Publish to nuget
#    run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json

   
 
