name: "build and deploy to nuget"

on: 
  push:
    branches:
    - 'master'
    tags:
    - 'v*'

env:
 VERSION: '1.0.0'

jobs:
 build_pack:  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3.0.0
  - name: Get tag
    id: latest-tag
    uses: actions-ecosystem/action-get-latest-tag@v1.6.0
    with:
      semver_only: true
  - name: Set version
    run: |
      echo "version=${{ steps.latest-tag.outputs.tag }}" >> $GITHUB_ENV
      echo $VERSION
      echo ${{ steps.latest-tag.outputs.tag }} | sed 's/[v]//g'
  
# - name: Get .Net
#   uses: actions/setup-dotnet@v2.0.0
#   with: 
#     dotnet-version: 6.x.x
# - name: restore packs
#   run: dotnet restore src\
# - name: Build
#   run: dotnet build --no-restore
# - name: Test
#   run: dotnet test --no-build --verbosity normal src\tests\tests.csproj

   
 
