name: "build and deploy to nuget"

on: 
  push:
    tags:
    - 'v*'

jobs:
 build_pack:  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3.0.0
  - name: Get tag
    id: latest-tag
    uses: actions-ecosystem/action-get-latest-tag@v1.6.0
    with:
      semver_only: true
  - name: Extract version
    id: extract-ver
    uses: frabert/replace-string-action@v2.0
    with:
      string: ${{ steps.latest-tag.outputs.tag }}
      pattern: v
      replace-with: ''
      
  - name: Set version
    run: |
      echo "ver=${{ steps.extract-ver.outputs.replaced }}" >> $GITHUB_ENV      
      echo ${{ env.ver }}
  
# - name: Get .Net
#   uses: actions/setup-dotnet@v2.0.0
#   with: 
#     dotnet-version: 6.x.x
# - name: restore packs
#   run: dotnet restore src\
# - name: Build
#   run: dotnet build --no-restore
# - name: Test
#   run: dotnet test --no-build --verbosity normal src\tests\tests.csproj

   
 
